/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-msg_ctrl_bladerf
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_MSG_CTRL_BLADERF_API_H
#define INCLUDED_MSG_CTRL_BLADERF_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_msg_ctrl_bladerf_EXPORTS
#define MSG_CTRL_BLADERF_API __GR_ATTR_EXPORT
#else
#define MSG_CTRL_BLADERF_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_MSG_CTRL_BLADERF_API_H */
