/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(msg_bladerf_src.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(01e2e45f47d813f432ea01fd1e6a5063)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/msg_ctrl_bladerf/msg_bladerf_src.h>
// pydoc.h is automatically generated in the build directory
#include <msg_bladerf_src_pydoc.h>

void bind_msg_bladerf_src(py::module& m)
{

    using msg_bladerf_src    = gr::msg_ctrl_bladerf::msg_bladerf_src;


    py::class_<msg_bladerf_src, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<msg_bladerf_src>>(m, "msg_bladerf_src", D(msg_bladerf_src))

        .def(py::init(&msg_bladerf_src::make),
           D(msg_bladerf_src,make)
        )
        



        ;




}








